name: Sync Github Repos To Gitee
on:
  push:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Organization mirror
        uses: Yikun/hub-mirror-action@master
        with:
          src: github/webapiclient
          dst: gitee/webapiclient
          dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
          dst_token: ${{ secrets.GITEE_TOKEN }}
          account_type: org
          debug: true
          force_update: true
