name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: board
        uses: gitboard-io/gitboard-action@main
        with:
          username: ezrealj
          key: ${{ secrets.GITBOARD }}
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: main
      - name: vuepress-deploy
        uses: EzrealJ/vuepress-deploy-node18@main
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          TARGET_REPO: WebApiClient/WebApiClient.github.io
          TARGET_BRANCH: gh-pages
          BUILD_SCRIPT: yarn && yarn docs:build
          BUILD_DIR: docs/.vuepress/dist/
